site_name: ICICLE Training Catalog
theme: 'readthedocs'

plugins:
    - search
    - awesome-pages
    - tags

extra_css:
  - css/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/