name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install --upgrade pip
      - run: pip install mkdocs-material==8.5.0
      - run: pip install mkdocs-awesome-pages-plugin==2.7.0
      - run: pip install pillow==9.0.1 cairosvg==2.5.2
      - run: pip install mkdocs-plugin-tags==0.2.2
      - run: pip install jinja2<3.1
      - run: mkdocs gh-deploy --force